<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\tModLoader.targets" />
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DefineConstants>$(DefineConstants);VSDEBUGMODE</DefineConstants>
	</PropertyGroup>
	<PropertyGroup>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<DocumentationFile>$(AssemblyName).xml</DocumentationFile>
	</PropertyGroup>
	<ItemGroup>
		<Reference Include="ArcaneOdysseyMusic">
			<HintPath>references\ArcaneOdysseyMusic.dll</HintPath>
		</Reference>
		<Reference Include="CalamityMod">
		  <HintPath>references\CalamityMod.dll</HintPath>
		</Reference>
		<Reference Include="Fargowiltas">
		  <HintPath>references\Fargowiltas.dll</HintPath>
		</Reference>
		<Reference Include="MagicStorage">
		  <HintPath>references\MagicStorage.dll</HintPath>
		</Reference>
		<Reference Include="StructureHelper">
		  <HintPath>references\StructureHelper.dll</HintPath>
		</Reference>
	</ItemGroup>
</Project>